#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_PartModifier_Backpack_M_CatBurglar

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.ApplyLevelParam
// 0x0018 (0x0018 - 0x0000)
struct B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam final
{
public:
	int32                                         Level;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMeshComponent*                         CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam) == 0x000008, "Wrong alignment on B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam");
static_assert(sizeof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam) == 0x000018, "Wrong size on B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam, Level) == 0x000000, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam::Level' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam, CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue) == 0x000008, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam::CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000010, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");

// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.ApplyOverrideToItems
// 0x0050 (0x0050 - 0x0000)
struct B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems final
{
public:
	TArray<class UFortItem*>                      Array;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItem*                              CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  CallFunc_GetItemGuid_ReturnValue;                  // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerControllerAthena*            CallFunc_GetAssociatedAthenaController_AsFort_Player_Controller_Athena; // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems) == 0x000008, "Wrong alignment on B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems");
static_assert(sizeof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems) == 0x000050, "Wrong size on B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, Array) == 0x000000, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::Array' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, CallFunc_Array_Length_ReturnValue) == 0x000010, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, Temp_int_Array_Index_Variable) == 0x000014, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, Temp_int_Loop_Counter_Variable) == 0x000018, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, CallFunc_Array_Get_Item) == 0x000020, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, CallFunc_GetItemGuid_ReturnValue) == 0x000028, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::CallFunc_GetItemGuid_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, CallFunc_Less_IntInt_ReturnValue) == 0x000038, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, CallFunc_Add_IntInt_ReturnValue) == 0x00003C, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, CallFunc_GetAssociatedAthenaController_AsFort_Player_Controller_Athena) == 0x000040, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::CallFunc_GetAssociatedAthenaController_AsFort_Player_Controller_Athena' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems, CallFunc_IsValid_ReturnValue) == 0x000048, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar
// 0x0098 (0x0098 - 0x0000)
struct B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable; // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetGameTimeInSeconds_ReturnValue;         // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMeshComponent*                         CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue; // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        CallFunc_GetAssociatedPlayerPawn_ReturnValue;      // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAsyncAction_CosmeticAdaptiveStatWatcher* CallFunc_WatchCosmeticStat_ReturnValue;      // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMeshComponent*                         CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_1; // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0062(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_63[0x1];                                       // 0x0063(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_2;            // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMeshComponent*                         CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_2; // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_StatName;                       // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_StatValue;                      // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_3;            // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMeshComponent*                         CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_3; // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_4;            // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName StatName, int32 StatValue)> K2Node_CreateDelegate_OutputDelegate_1;   // 0x008C(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar) == 0x000008, "Wrong alignment on B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar");
static_assert(sizeof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar) == 0x000098, "Wrong size on B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, EntryPoint) == 0x000000, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::EntryPoint' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000004, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000018, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, Temp_bool_Has_Been_Initd_Variable) == 0x000020, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, Temp_bool_IsClosed_Variable) == 0x000021, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, Temp_bool_Has_Been_Initd_Variable_1) == 0x000022, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable) == 0x000023, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::Temp_bool_Whether_the_gate_is_currently_open_or_close_Variable' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_GetGameTimeInSeconds_ReturnValue) == 0x000024, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_GetGameTimeInSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue) == 0x000028, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_GetAssociatedPlayerPawn_ReturnValue) == 0x000030, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_GetAssociatedPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_WatchCosmeticStat_ReturnValue) == 0x000038, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_WatchCosmeticStat_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_IsValid_ReturnValue) == 0x000040, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, Temp_bool_IsClosed_Variable_1) == 0x000041, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_1) == 0x000048, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, Temp_name_Variable) == 0x000050, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, Temp_int_Variable) == 0x000054, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_Max_ReturnValue) == 0x000058, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x00005C, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_Less_IntInt_ReturnValue) == 0x000060, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_Greater_IntInt_ReturnValue) == 0x000061, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_BooleanAND_ReturnValue) == 0x000062, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_Conv_IntToFloat_ReturnValue_2) == 0x000064, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_Conv_IntToFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_2) == 0x000068, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, K2Node_CustomEvent_StatName) == 0x000070, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::K2Node_CustomEvent_StatName' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, K2Node_CustomEvent_StatValue) == 0x000074, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::K2Node_CustomEvent_StatValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_Conv_IntToFloat_ReturnValue_3) == 0x000078, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_Conv_IntToFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_3) == 0x000080, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, CallFunc_Conv_IntToFloat_ReturnValue_4) == 0x000088, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::CallFunc_Conv_IntToFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar, K2Node_CreateDelegate_OutputDelegate_1) == 0x00008C, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");

// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.GetAssociatedAthenaController
// 0x0058 (0x0058 - 0x0000)
struct B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController final
{
public:
	class AFortPlayerControllerAthena*            AsFort_Player_Controller_Athena;                   // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        CallFunc_GetAssociatedPlayerPawn_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetVehicleActor_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerControllerAthena*            K2Node_DynamicCast_AsFort_Player_Controller_Athena; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  K2Node_DynamicCast_AsPawn;                         // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetController_ReturnValue_1;              // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerControllerAthena*            K2Node_DynamicCast_AsFort_Player_Controller_Athena_1; // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController) == 0x000008, "Wrong alignment on B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController");
static_assert(sizeof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController) == 0x000058, "Wrong size on B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, AsFort_Player_Controller_Athena) == 0x000000, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::AsFort_Player_Controller_Athena' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, CallFunc_GetAssociatedPlayerPawn_ReturnValue) == 0x000008, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::CallFunc_GetAssociatedPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, CallFunc_GetController_ReturnValue) == 0x000010, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, CallFunc_GetVehicleActor_ReturnValue) == 0x000018, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::CallFunc_GetVehicleActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, K2Node_DynamicCast_AsFort_Player_Controller_Athena) == 0x000020, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::K2Node_DynamicCast_AsFort_Player_Controller_Athena' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, K2Node_DynamicCast_AsPawn) == 0x000030, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::K2Node_DynamicCast_AsPawn' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, K2Node_DynamicCast_bSuccess_1) == 0x000038, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, CallFunc_GetController_ReturnValue_1) == 0x000040, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::CallFunc_GetController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, K2Node_DynamicCast_AsFort_Player_Controller_Athena_1) == 0x000048, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::K2Node_DynamicCast_AsFort_Player_Controller_Athena_1' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController, K2Node_DynamicCast_bSuccess_2) == 0x000050, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");

// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.OnStatChanged_ADEC84754D9C14E63858F5A170B97A58
// 0x0008 (0x0008 - 0x0000)
struct B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58 final
{
public:
	class FName                                   StatName;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         StatValue;                                         // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58) == 0x000004, "Wrong alignment on B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58");
static_assert(sizeof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58) == 0x000008, "Wrong size on B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58, StatName) == 0x000000, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58::StatName' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58, StatValue) == 0x000004, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58::StatValue' has a wrong offset!");

// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.UserConstructionScript
// 0x0018 (0x0018 - 0x0000)
struct B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript final
{
public:
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMeshComponent*                         CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMeshComponent*                         CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_1; // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript) == 0x000008, "Wrong alignment on B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript");
static_assert(sizeof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript) == 0x000018, "Wrong size on B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000000, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x000004, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript, CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue) == 0x000008, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript::CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript, CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_1) == 0x000010, "Member 'B_Athena_PartModifier_Backpack_M_CatBurglar_C_UserConstructionScript::CallFunc_GetSkeletalMeshForAssociatedPlayerPawnPartType_ReturnValue_1' has a wrong offset!");

}

