#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_PartModifier_Backpack_M_CatBurglar

#include "Basic.hpp"

#include "B_Athena_PartModifier_Backpack_M_CatBurglar_classes.hpp"
#include "B_Athena_PartModifier_Backpack_M_CatBurglar_parameters.hpp"


namespace SDK
{

// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.ApplyLevelParam
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::ApplyLevelParam(int32 Level)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "ApplyLevelParam");

	Params::B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyLevelParam Parms{};

	Parms.Level = Level;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.ApplyOverrideToItems
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UFortItem*>&               Array                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::ApplyOverrideToItems(TArray<class UFortItem*>& Array)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "ApplyOverrideToItems");

	Params::B_Athena_PartModifier_Backpack_M_CatBurglar_C_ApplyOverrideToItems Parms{};

	Parms.Array = std::move(Array);

	UObject::ProcessEvent(Func, &Parms);

	Array = std::move(Parms.Array);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar");

	Params::B_Athena_PartModifier_Backpack_M_CatBurglar_C_ExecuteUbergraph_B_Athena_PartModifier_Backpack_M_CatBurglar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.GetAssociatedAthenaController
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena**     AsFort_Player_Controller_Athena                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::GetAssociatedAthenaController(class AFortPlayerControllerAthena** AsFort_Player_Controller_Athena)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "GetAssociatedAthenaController");

	Params::B_Athena_PartModifier_Backpack_M_CatBurglar_C_GetAssociatedAthenaController Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsFort_Player_Controller_Athena != nullptr)
		*AsFort_Player_Controller_Athena = Parms.AsFort_Player_Controller_Athena;
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.HackyWorkaroundRefreshTimerGuy
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::HackyWorkaroundRefreshTimerGuy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "HackyWorkaroundRefreshTimerGuy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.InitializeVariabels
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::InitializeVariabels()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "InitializeVariabels");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.OnActualStatChange
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::OnActualStatChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "OnActualStatChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.OnPawnAndPartChanged
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::OnPawnAndPartChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "OnPawnAndPartChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.OnPostResIn
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::OnPostResIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "OnPostResIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.OnStatChanged_ADEC84754D9C14E63858F5A170B97A58
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             StatName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   StatValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::OnStatChanged_ADEC84754D9C14E63858F5A170B97A58(class FName StatName, int32 StatValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "OnStatChanged_ADEC84754D9C14E63858F5A170B97A58");

	Params::B_Athena_PartModifier_Backpack_M_CatBurglar_C_OnStatChanged_ADEC84754D9C14E63858F5A170B97A58 Parms{};

	Parms.StatName = StatName;
	Parms.StatValue = StatValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.ResetSafetyGate
// (BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::ResetSafetyGate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "ResetSafetyGate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Athena_PartModifier_Backpack_M_CatBurglar.B_Athena_PartModifier_Backpack_M_CatBurglar_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_Athena_PartModifier_Backpack_M_CatBurglar_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Athena_PartModifier_Backpack_M_CatBurglar_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

