#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace BP_Shotgun_SG_BFPA { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_AssaultRifle_FrontClip_SideAction { struct FAnimBlueprintGeneratedConstantData; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace SK_MachineGun_Clip_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace Blueprint_Paper_VIM { struct FAnimBlueprintGeneratedConstantData; }

namespace M_MED_Cat_Burglar_Human_FaceAcc_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Fortnite_Player_FullBody_LinkedGraph_Template { struct FAnimBlueprintGeneratedConstantData; }

namespace Mechanical_Engineer_Female_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace M_MED_Cat_Burglar_Human_Head_01_Skeleton_AnimBP_Child { struct FAnimBlueprintGeneratedConstantData; }

namespace ButtonStyle_Empty { class UButtonStyle_Empty_C; }

namespace M_MED_Cat_Burglar_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_Ramirez_Fallback_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace Earpiece_Gadget_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Fringe_Plank_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_AssaultRifle_FrontClip_BackAction { struct FAnimBlueprintGeneratedConstantData; }

namespace ButtonStyle_Empty_0 { class UButtonStyle_Empty_C; }


namespace Galileo_LobsterLayerAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace HighTower_Tapas_Axe_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_Player_PostProcessProceduralFixUp_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_M_Avg_Player_Goop_AnimBlueprint
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_M_Avg_Player_ZipLine_AnimBlueprint
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_SkyDiveAndGlide_AnimBlueprint
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_Player_DBNOCarried_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_M_Avg_Player_AnimBlueprint
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace MenuScreen_Athena
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_M_Avg_Player_DBNO_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace SwimmingAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace B_MasterPetAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace B_AnimBP_HightowerRadish
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_Base_Head_Export_Skeleton_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_M_Avg_Player_Sprint_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace SlidingLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Fortnite_Player_LowerBodyJog_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
